// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace rumda.Protocol
{

public enum MessageId : ushort
{
 GS2C_Test = 6990,
 GS2C_Echo = 6999,
};


}
